// Generated by CoffeeScript 1.6.3
(function() {
  var AService, AppController, app, routeConfig;

  AService = (function() {
    function AService($http) {
      this.$http = $http;
    }

    AService.prototype.fetch = function() {
      return this.$http.post('data.json');
    };

    return AService;

  })();

  AppController = (function() {
    function AppController(aService) {
      this.aService = aService;
      debugger;
      aService.fetch();
    }

    return AppController;

  })();

  routeConfig = function($provide, $routeProvider, $locationProvider) {
    $provide.decorator('$sniffer', [
      '$delegate', function($delegate) {
        $delegate.history = false;
        return $delegate;
      }
    ]);
    $routeProvider.when('/foo', {
      template: '<div>woop!</div>',
      controller: 'AppController'
    });
    $routeProvider.otherwise({
      redirectTo: '/foo'
    });
    return $locationProvider.html5Mode(true);
  };

  angular.module('app', ['ngRoute']);

  app = angular.module('app');

  app.config(['$provide', '$routeProvider', '$locationProvider', routeConfig]);

  app.service('aService', ['$http', AService]);

  app.controller('AppController', ['aService', AppController]);

}).call(this);
